version: "3.3"

services:
  redis:
    image: redis:alpine
    ports:
      - "16379:6379"

  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app/src
    depends_on:
      - redis
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]

  tests:
    build: .
    environment:
      - PYTHONPATH=/app/src
      - TESTING=1
    depends_on:
      - redis
    command: ["pytest", "-v", "-p", "no:warnings", "-r", "w"]

